ZSH_THEME="robbyrussell"

export ZSH="$HOME/.oh-my-zsh"
export THIS="$HOME/.config/zsh"
export PATH="$HOME/.config/bin:$PATH"

source $ZSH/oh-my-zsh.sh
source ~/.nvm/nvm.sh
source $THIS/aliases
source $THIS/functions
